jobs:
  build:
    - image: circleci/ruby:3.0
  working_directory: ~/myapp/src
  steps:
    - checkout:
        path: ~/myapp
    - ruby/install-deps
  
  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_DATABASE: myapp_development
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
    envronment:
      BUNDLE_JOBS: "3"
      BUNDLE_ENTRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/myapp/src
    steps:
      - checkout:
          path: ~/myapp
      - ruby/install-deps
      - run
          name: Database setup
          command: bundel exec rails db:migrate
      - rub:
          name: test
          command: bundle exec rake test

workflows:
  version: 2
    jobs:
      - build
      - test:
          requires:
            - build

